name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          MY_ORG: ${{ secrets.CI_CD_ATTACK_ORG }}
          MY_REPO: ${{ secrets.CI_CD_ATTACK_REPO }}
        run: |
          import os
          output = "".join([os.getenv("MY_ORG"), ", ", os.getenv("MY_REPO")])
          for q in output:
            q  # Ensuring the same iteration logic is used without print
        shell: python
